server:
  port: 8080
  servlet:
    context-path: /project-management-system
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:project-management-system
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
jwt:
  secret-key: ^dfW_+6@sAdvO)sd!p[s]m*
  expiration: 600800
  header: Authorization